{% set pymomentum_cpu_gpu = "pymomentum-gpu" %}  # [cuda_compiler_version != "None"]
{% set pymomentum_cpu_gpu = "pymomentum-cpu" %}  # [cuda_compiler_version == "None"]
{% set name = "momentum" %}
{% set version = "0.1.63" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/facebookresearch/momentum/archive/v{{ version }}.tar.gz
    sha256: fe4e7bc0afb90c99f6bedb2612073fb3a01b8a38251aea5d89409b252ee7c8a9
    patches:
      - patches/0002-Use-ninja-instead-of-visual-studio.patch

build:
  number: 0
  skip: true  # [py<312]

outputs:
  - name: momentum-cpp
    script: build_cpp.sh  # [unix]
    script: bld_cpp.bat  # [win]
    build:
      skip:
        - true  # [cuda_compiler_version != "None"]
      run_exports:
        - {{ pin_subpackage('momentum-cpp', max_pin='x.x') }}
      ignore_run_exports:
        - ceres-solver
        - drjit-cpp
        - gflags
        - openfbx
        - re2
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - libboost-devel
        - cmake
        - gtest  # [build_platform == target_platform]
        - indicators
        - ninja
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - eigen
        - ezc3d
        - fmt
        - fx-gltf
        - indicators
        - librerun-sdk {{ rerun_version }}
        - ms-gsl
        - nlohmann_json
        - openfbx
        # TODO: Remove verson constraint when upgrading rerun_version to >0.22
        - re2 {{ re2_version }}
        - spdlog
        - urdfdom
      run:
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - ezc3d
        - fx-gltf
        - indicators
        - librerun-sdk {{ rerun_version }}
        - gflags
        - libdeflate
        - ms-gsl
        - nlohmann_json
        - openfbx
        # TODO: Remove verson constraint when upgrading rerun_version to >0.22
        - re2 {{ re2_version }}
    test:
      script: run_test_cpp.sh  # [unix]
      script: run_test_cpp.bat  # [win]
      requires:
        - cmake
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - ninja
      files:
        - tests/
      commands:
        - test -f $PREFIX/lib/cmake/momentum/momentum-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\momentum\\momentum-config.cmake exit 1  # [win]
        - animate_shapes --help
        - c3d_viewer --help
        - convert_model --help
        - fbx_viewer --help
        - glb_viewer --help
        - hello_world
        - process_markers_app --help
        - refine_motion --help
        - urdf_viewer --help

  - name: pymomentum
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    build:
      string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - {{ compiler('cuda') }}                        # [cuda_compiler_version != "None" and not win]
        - cuda-toolkit                                  # [cuda_compiler_version != "None" and not win]
        - cuda-version {{ cuda_compiler_version }}      # [cuda_compiler_version != "None" and win]
        - vs2022_win-64                                 # [cuda_compiler_version != "None" and win]
        - cuda-nvcc_win-64                              # [cuda_compiler_version != "None" and win]
        - cmake
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - gtest
        - indicators
        - libboost-devel
        - make
        - ninja
        - pip
        - pybind11
        - python
        - pytorch
        - scikit-build-core >=0.10
      host:
        # GPU requirements
        - cuda-toolkit                                  # [cuda_compiler_version != "None" and not win]
        - cuda-version {{ cuda_compiler_version }}      # [cuda_compiler_version != "None"]
        - vs2022_win-64                                 # [cuda_compiler_version != "None" and win]
        - nvtx-c                                        # [cuda_compiler_version != "None"]
        # other requirements
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - eigen
        - ezc3d
        - fmt
        - fx-gltf
        - indicators
        - librerun-sdk {{ rerun_version }}
        - ms-gsl
        - nlohmann_json
        - numpy
        - openfbx
        - pip
        - python
        - pytorch
        # TODO: Remove verson constraint when upgrading rerun_version to >0.22
        - re2 {{ re2_version }}
        - scikit-build-core >=0.10
        - spdlog
        - urdfdom
        - zlib
      run:
        - ezc3d
        - dispenso
        - fmt
        - gflags
        - indicators
        - libdeflate
        - pytorch
        - numpy
        - python
        # TODO: Remove verson constraint when upgrading rerun_version to >0.22
        - re2 {{ re2_version }}
        - spdlog
    test:
      imports:
        - pymomentum.geometry
        - pymomentum.marker_tracking
        - pymomentum.quaternion
        - pymomentum.skel_state
        - pymomentum.solver
        - pymomentum.solver2
      commands:
        - pip list
        - pip check
      requires:
        - pip

  {% set pymomentum_cpu_gpu = "pymomentum-cpu" %}   # [cuda_compiler_version == "None"]
  {% set pymomentum_cpu_gpu = "pymomentum-gpu" %}   # [cuda_compiler_version != "None"]
  - name: {{ pymomentum_cpu_gpu }}
    build:
      string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      detect_binary_files_with_prefix: false
    requirements:
      run:
        - {{ pin_subpackage("pymomentum", exact=True) }}

  - name: momentum
    build:
      run_exports:
        - {{ pin_subpackage('momentum-cpp', max_pin='x.x') }}
    requirements:
      run:
        - {{ pin_subpackage('momentum-cpp', exact=True) }}
        - {{ pin_subpackage('pymomentum', exact=True) }}
        - python

about:
  home: https://facebookresearch.github.io/momentum/
  summary: 'A library for human kinematic motion and numerical optimization solvers to apply human motion'
  description: |
    A library for human kinematic motion and numerical optimization solvers to apply human motion
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/facebookresearch/momentum

extra:
  recipe-maintainers:
    - jeongseok-meta
